language: python
python:
- 3.6
install:
- pip install .
script:
- make
notifications:
  email:
  - xiaoxiang.cn@gmail.com
  - xiaoxiang_cn@qq.com
deploy:
  provider: pypi
  on:
    repo: oriole-island/oriole-service
  distributions: bdist_wheel
  user: zhouxiaoxiang
  password:
    secure: tiB8gRhtFU46RZO1KhtQnqkD/vnAHq/HbzXRKyFkpQlXJpo2JcwUxXuzT5Fn20xSR06EwXCHarkEQSAPmwf3J3e+DmkxtmRRAQE9wr12nXxYlne4jri6we4/XRhhhAdf2SvSWCeAbZNq3g8ovr+TK7ooprcnddvRUr1SzWcUJzPbw+2q50SvNtpNSWV5DDDf0na/rg4H4OxpnBLmk5tD2NILNVCESnRzIzEgj5/bEo5pGANSod4JuykT1gxGfqbpp9i4ny3E5aVDNz+Lm2032MuceieIyQoLkfbXQcSjKv4+QjFMjVpXNoRlBjA0l7BZJJM3P+GFudYMBTS7gri6digeP71UvZSp8TCEKtxdFvidTdiLlC7uKh4ZoDYxNSj76uFEMQH2TJ7lbZ5bw+6s6ejlgnExUC2CgT3h3oKDUqf/5zJ9XCSM9T6WEoDdpokKbKC1/x99l2YyrCj3yXB8wOU1gQfu4LCJdM3/YNWb8pUeL+ouMwHz16fMxOHVUjwnrc01spJ+KTg4Xsf7FSx7ONPu+debMzRfoTNHsHE0FUM4cnkbWkhjUIe1L+SSayfs4gG0dng3tdaUqLWXMSBkKfJaE1KK1eTYC/OmZi0XwHjzedDK1xoTL9QXdm/hmlCYhk6gF0JodStqM71OFFaTseKIFd1FIC6WjEHuspchFP0=
